# Generated by Django 5.1.5 on 2025-07-11 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateTimeField(auto_now=True)),
                (
                    "Gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Female",
                        max_length=8,
                        null=True,
                    ),
                ),
                ("DOB", models.DateField(null=True)),
                ("About", models.TextField(blank=True, max_length=200, null=True)),
                ("Contact1", models.CharField(max_length=15, null=True)),
                ("Contact2", models.CharField(blank=True, max_length=15, null=True)),
                ("City", models.CharField(max_length=50, null=True)),
                ("Country", models.CharField(max_length=50, null=True)),
                ("Latitude", models.CharField(max_length=200, null=True)),
                ("Longitude", models.CharField(max_length=200, null=True)),
                ("Instagram", models.CharField(blank=True, max_length=100, null=True)),
                ("Facebook", models.CharField(blank=True, max_length=100, null=True)),
                ("X", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "User",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
