# Generated by Django 5.1.5 on 2025-07-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="Photo",
            field=models.ImageField(null=True, upload_to="photo"),
        ),
    ]
