# Generated by Django 5.1.5 on 2025-08-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_profile_city_alter_profile_contact1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="About",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
