# Generated by Django 5.1.5 on 2025-08-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_profile_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="Photo",
            field=models.ImageField(null=True, upload_to="photo/profilePhoto"),
        ),
    ]
