# Generated by Django 5.1.5 on 2025-08-15 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0001_initial"),
        ("users", "0005_alter_profile_photo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductVideo",
            new_name="Video",
        ),
    ]
