# Generated by Django 5.1.5 on 2025-08-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0002_rename_productvideo_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="Description",
            field=models.TextField(default="", max_length=160),
        ),
    ]
